### PR TITLE
Create wallet flow with new designs (happy path)

### PR DESCRIPTION
**Pull request by tw0po1nt**
# Screenshots
Simulator Screen Shot - iPhone 14 Pro Max - 2023-04-11 at 20 33 57

Simulator Screen Shot - iPhone 14 Pro Max - 2023-04-11 at 20 34 05

Simulator Screen Shot - iPhone 14 Pro Max - 2023-04-11 at 20 34 24

Simulator Screen Shot - iPhone 14 Pro Max - 2023-04-11 at 20 35 00

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [x] Does the code abide by the [Coding Guidelines](../blob/main/docs/CODING_GUIDELINES.md)?
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [x] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [x] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [x] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [x] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [x] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/main/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage before and after your changes and when possible, leave it in a better place. [Learn More...](../blob/main/docs/testing/local_coverage.md)_
- [x] Documentation: Did you review Docs, [README.md](../blob/main/README.md), [LICENSE.md](../blob/main/LICENSE.md), and [Architecture.md](../blob/main/docs/Architecture.md) as appropriate?
- [x] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

### CODE REVIEW

**Review by BostonZcash — COMMENTED** [review]
This is looking good on my iPhone 14 emulator.

**Working:**
- Seed generation / wallet creation flow.
- 'I confirm I have saved my seed phrase' requirement.
- 'Export as PDF' functionality.
- Seed produces same zs1 address when imported to external wallets. (Still need to decode the UAs to compare the Orchard addresses. The second-generated t1 address on Zecwallet Lite was that of the new Nighthawk wallet.)

**Not working (perhaps as expected from screenshots):**
- 'Restore from backup' (does not advance flow)
- 'Terms and Conditions' link (not clickable)

**Suggestions / Notes:**
- Remove 'try to' from 'Get started' text. Suggests lack of confidence on ability to restore a properly backed up seed.
- Exported seed PDF is a screenshot (in PDF form). Consider a standardised format (A4 / Letter) with logotype and explanatory text.

**Comment by tw0po1nt** [comment]
@BostonZcash Restore wallet is out of scope for this particular PR. I had planned it for a different PR. I'll wire up the T&Cs, I think I just passed over it because I was focused on laying things out. 

For the PDF, is that what the Android app is currently doing?

**Comment by BostonZcash** [comment]
> For the PDF, is that what the Android app is currently doing?

The Android app creates a letter-sized PDF document: 'These are the seed words used to restore your Zcash in Nighthawk Wallet:'

However, it's not offered in the initial wallet creation flow, but rather under 'Settings > Backup your wallet > Save as PDF' (and also requires the PDF be password-protected).

**Comment by BostonZcash** [comment]
With these commits, the T&C link is now working, and the exported PDF matches that of the Android app.

However, I'm finding that the 'Continue' button on the seed phrase screen no longer advances the flow. (This is regardless of whether a PDF has been exported or the T&C link followed.)

Instead, debug logs produce upon 'Continue' button click:

```
2023-04-18 21:47:00.345279-0400 secant-mainnet[32963:4645779] [tcaLogs] received action:
  RootReducer.Action.phraseDisplay(.finishedPressed)
  (No state changes)
```

**Comment by BostonZcash** [comment]
'Continue' button now advances the screen flow. However, upon first wallet creation attempt, I encountered a missing 19th word (screenshot). This also inverted the 20th and 21st seed words.

As the 'backup wallet' option under Settings does not yet display the seed phrase or PDF option, I was unable to verify if this displayed the missing word. I suspect this was the result of a longer word than spacing allowed, as I've since been unable to replicate with subsequent wallet generations.

missing-19

**Review by BostonZcash — APPROVED** [review]
Flow working as expected with the latest commit. (Have not been able to replicate the '19th word' issue previously reported, despite numerous wallet generations.)

**Pull request merged**
